HomebrewRPG.WebMVC/Controllers/CharacterController.cs
using HomebrewRPG.Data;
using HomebrewRPG.Models;
using HomebrewRPG.Models.CharacterItemModels;
using HomebrewRPG.Models.CharacterSpell;
using HomebrewRPG.Models.CharacterWardrobeModels;
using HomebrewRPG.Models.CharacterWeaponModels;
using HomebrewRPG.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace HomebrewRPG.WebMVC.Controllers
{
    [Authorize]
    public class CharacterController : Controller
    {
        // GET: Character
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CharacterService(userId);
            var model = service.GetCharacters();
            return View(model);
        }

        //GET
        public ActionResult Create()
        {
            ViewBag.Title = "New Character";

            List<string> magicTypes = new List<string>()
            {
                "charisma",
                "intelligence",
                "instinct",
                "non-magic"
            };
            var magicQuery = from o in magicTypes
                             select new SelectListItem()
                             {
                                 Value = o,
                                 Text = o
                             };
            ViewBag.MagicType = magicQuery.ToList();

            List<string> prowessTypes = new List<string>()
            {
                "agility",
                "strength"
            };
            var prowessQuery = from o in prowessTypes
                               select new SelectListItem()
                               {
                                   Value = o,
                                   Text = o
                               };
            ViewBag.ProwessType = prowessQuery.ToList();

            var model =
                new CharacterCreate
                {
                    CharacterLevel = 1,
                    Health = 0,
                    Strength = 0,
                    Instinct = 0,
                    Agility = 0,
                    Intelligence = 0,
                    Charisma = 0,

                    Endurance = 0,
                    Constitution = 0,
                    Athletics = 0,
                    Tenacity = 0,
                    Acrobatics = 0,
                    SleightOfHand = 0,
                    Sneak = 0,
                    Willpower = 0,
                    Investigation = 0,
                    Knowledge = 0,
                    Bravery = 0,
                    Pilotry = 0,
                    Insight = 0,
                    Perception = 0,
                    Survival = 0,
                    Faith = 0,
                    Deception = 0,
                    Diplomacy = 0,
                    Intimidation = 0,
                    Performance = 0,
                    Seduction = 0,
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CharacterCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateCharacterService();
            if (service.CreateCharacter(model))
            {
                TempData["SaveResult"] = "Your character was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Character could not be created.");

            return View("Index");
        }

        private CharacterService CreateCharacterService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CharacterService(userId);
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateCharacterService();
            var model = svc.GetCharacterById(id);

            return View(model);
        }

        public ActionResult CharacterSheet(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var characterService = new CharacterService(userId);
            var characterItemService = new CharacterItemService(userId);
            var characterWeaponService = new CharacterWeaponService(userId);
            var characterWardrobeItemService = new CharacterWardrobeService(userId);
            var characterSpellService = new CharacterSpellService(userId);
            var walletService = new WalletService(userId);


            CharacterSheetModel model = new CharacterSheetModel();
            model.CharacterDetail = characterService.GetEditCharacterById(id);
            model.BonusesDetail = characterService.GetCharacterById(id);
            model.Wallet = walletService.GetWalletByCharacterId(id);


            model.UntrainedHealth = (model.CharacterDetail.Health * 2) + model.CharacterDetail.Instinct;
            model.UntrainedStrength = (model.CharacterDetail.Strength * 2) + model.CharacterDetail.Instinct;
            model.UntrainedInstinct = (model.CharacterDetail.Instinct * 2) + model.CharacterDetail.Instinct;
            model.UntrainedAgility = (model.CharacterDetail.Agility * 2) + model.CharacterDetail.Instinct;
            model.UntrainedIntelligence = (model.CharacterDetail.Intelligence * 2) + model.CharacterDetail.Instinct;
            model.UntrainedCharisma = (model.CharacterDetail.Charisma * 2) + model.CharacterDetail.Instinct;


            var itemList = characterItemService.GetCharacterItemsByCharacterId(id);
            foreach (var x in itemList)
            {
                CharacterItemDetail y = new CharacterItemDetail();
                {
                    y.CharacterItemId = x.CharacterItemId;
                    y.CharacterId = x.CharacterId;
                    y.ItemId = x.ItemId;
                    y.Quantity = x.Quantity;
                    y.ItemName = x.ItemName;
                    y.ItemDescription = x.ItemDescription;
                };
                model.Items.Add(y);
            }

            var spellList = characterSpellService.GetCharacterSpellsByCharacterId(id);
            foreach (var x in spellList)
            {
                CharacterSpellDetail y = new CharacterSpellDetail();
                {
                    y.CharacterSpellId = x.CharacterSpellId;
                    y.CharacterId = x.CharacterId;
                    y.SpellId = x.SpellId;

                    y.SpellName = x.SpellName;
                    y.SpellDescription = x.SpellDescription;
                    y.SpellEffect = x.SpellEffect;
                    y.SpellType = x.SpellType;
                    y.Range = x.Range;
                    y.SpellDC = x.SpellDC;
                };
                model.Spells.Add(y);
            }

                var weaponList = characterWeaponService.GetCharacterWeaponsByCharacterId(id);
            foreach (var x in weaponList)
            {
                CharacterWeaponDetail y = new CharacterWeaponDetail();
                {
                    y.CharacterWeaponId = x.CharacterWeaponId;
                    y.CharacterId = x.CharacterId;
                    y.CharacterWeaponId = x.CharacterWeaponId;
                    y.WeaponId = x.WeaponId;
                    y.IsEquipped = x.IsEquipped;

                    y.WeaponName = x.WeaponName;
                    y.Description = x.Description;
                    y.WeaponType = x.WeaponType;
                    y.DamageDice = x.DamageDice;
                    y.DamageModifier = x.DamageModifier;
                    y.ProwessBonus = x.ProwessBonus;
                    y.Range = x.Range;
                    y.CriticalRange = x.CriticalRange;
                    y.Special = x.Special;

                    if (x.IsEquipped)
                    {
                        model.BonusesDetail.Health += x.Health;
                        model.BonusesDetail.Strength += x.Strength;
                        model.BonusesDetail.Instinct += x.Instinct;
                        model.BonusesDetail.Agility += x.Agility;
                        model.BonusesDetail.Intelligence += x.Intelligence;
                        model.BonusesDetail.Charisma += x.Charisma;

                        model.BonusesDetail.HitPoints += x.HitPoints;
                        model.BonusesDetail.Sanity += x.Sanity;
                        model.BonusesDetail.Dodge += x.Dodge;
                        model.BonusesDetail.Reaction += x.Reaction;
                        model.BonusesDetail.Magic += x.Magic;
                        model.BonusesDetail.BaseProwess += x.ProwessBonus;
                        model.BonusesDetail.Fate += x.Fate;

                        model.BonusesDetail.Endurance += x.Endurance;
                        model.BonusesDetail.Constitution += x.Constitution;
                        model.BonusesDetail.Athletics += x.Athletics;
                        model.BonusesDetail.Tenacity += x.Tenacity;
                        model.BonusesDetail.Acrobatics += x.Acrobatics;
                        model.BonusesDetail.SleightOfHand += x.SleightOfHand;
                        model.BonusesDetail.Sneak += x.Sneak;
                        model.BonusesDetail.Willpower += x.Willpower;
                        model.BonusesDetail.Investigation += x.Investigation;
                        model.BonusesDetail.Knowledge += x.Knowledge;
                        model.BonusesDetail.Bravery += x.Bravery;
                        model.BonusesDetail.Pilotry += x.Pilotry;
                        model.BonusesDetail.Insight += x.Insight;
                        model.BonusesDetail.Perception += x.Perception;
                        model.BonusesDetail.Survival += x.Survival;
                        model.BonusesDetail.Faith += x.Faith;
                        model.BonusesDetail.Deception += x.Deception;

HomebrewRPG.WebMVC/Controllers/CharacterSpellController.cs
using HomebrewRPG.Models;
using HomebrewRPG.Models.CharacterSpell;
using HomebrewRPG.Models.SpellModels;
using HomebrewRPG.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomebrewRPG.WebMVC.Controllers
{
    public class CharacterSpellController : Controller
    {
        // GET: CharacterSpell
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            ViewBag.Title = "New CharacterItem";

            var userId = Guid.Parse(User.Identity.GetUserId());
            var characterService = new CharacterService(userId);
            var spellService = new SpellService(userId);

            List<CharacterListItem> characters = characterService.GetCharacters().ToList();
            var queryCharacter = from o in characters
                                 select new SelectListItem()
                                 {
                                     Value = o.CharacterId.ToString(),
                                     Text = o.CharacterName
                                 };
            ViewBag.CharacterId = queryCharacter.ToList();

            List<SpellListItem> spells = spellService.GetSpells().ToList();
            var queryItem = from o in spells
                            select new SelectListItem()
                            {
                                Value = o.SpellId.ToString(),
                                Text = o.SpellName
                            };
            ViewBag.SpellId = queryItem.ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CharacterSpellCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateCharacterSpellService();
            if (service.CreateCharacterSpell(model))
            {
                TempData["SaveResult"] = "Your spell was added.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Item could not be added.");

            return View("Index");
        }

        private CharacterSpellService CreateCharacterSpellService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CharacterSpellService(userId);
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateCharacterSpellService();
            var model = svc.GetCharacterSpellById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var svc = CreateCharacterSpellService();
            var detail = svc.GetCharacterSpellById(id);
            var model =
                new CharacterSpellEdit
                {
                    CharacterSpellId = detail.CharacterSpellId,
                    CharacterId = detail.CharacterId,
                    SpellId = detail.SpellId,
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CharacterSpellEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.SpellId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateCharacterSpellService();
            if (service.UpdateCharacterSpell(model))
            {
                TempData["SaveResult"] = "Updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your request could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCharacterSpellService();
            var model = svc.GetCharacterSpellById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var svc = CreateCharacterSpellService();
            svc.DeleteCharacterSpell(id);

            TempData["SaveResult"] = "Your spell was removed";

            return RedirectToAction("Index");
        }
    }
}

HomebrewRPG.WebMVC/Views/CharacterSpell/Create.cshtml
@model HomebrewRPG.Models.CharacterSpell.CharacterSpellCreate

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal padding">
        <h4>Add Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SpellId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SpellId, ViewBag.SpellId as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpellId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CharacterId, ViewBag.CharacterId as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CharacterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="row padding">
    <a href='@Url.Action("Index", "Character")' class="btn btn-default btn-sm">Back to Characters</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomebrewRPG.WebMVC/Views/CharacterSpell/Delete.cshtml
@model HomebrewRPG.Models.CharacterSpell.CharacterSpellDetail

@{
    ViewBag.Title = "Delete";
}

<div class="row padding">

    <div class="col-sm-12 col-md-6 col-md-offset-2 text-center">
        <h2>Delete</h2>

        <h3>Are you sure you want to remove this spell from your spellbook?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.SpellName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SpellName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.SpellDescription)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SpellDescription)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="row padding">
                    <input type="submit" value="Remove Spell" class="btn bg-danger" />
                </div>
            }
        <a href='@Url.Action("CharacterSheet", "Character", new { id = Model.CharacterId })' class="btn btn-default">Back to Character</a>
        </div>
    </div>
</div>

HomebrewRPG.WebMVC/Views/CharacterSpell/Edit.cshtml
@model HomebrewRPG.Models.CharacterSpell.CharacterSpellEdit

@{
    ViewBag.Title = "Edit";
}


@using(Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharacterSpellId)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharacterId)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SpellId)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <p>Jokes, you can only delete it.</p>

        <div class="form-group">
            <div class="row">
                <div class="col-md-offset-2 col-md-4 padding">
                    <input type="submit" value="Save" class="btn btn-default hidden" />
                </div>
                <div class="col-md-6 padding">
                    <a href='@Url.Action("Delete", "CharacterSpell", new { id = Model.CharacterSpellId })'><i class="fa fa-trash fa-lg"></i></a>
                </div>
            </div>
        </div>
    </div>
}

<div class="row padding">
    <a href='@Url.Action("CharacterSheet", "Character", new { id = Model.CharacterId })' class="btn btn-default btn-sm">Back to Character</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomebrewRPG.WebMVC/Views/CharacterSpell/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="padding">The change was made!</h2>

<div class="row padding">
    <button class="btn btn-default" onclick="goBack()">Back to Character</button>

    <script>
function goBack() {
  window.history.go(-2);
}
    </script>
</div>