HomebrewRPG.WebMVC/Controllers/HeroicController.cs
using HomebrewRPG.Models.HeroicModels;
using HomebrewRPG.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomebrewRPG.WebMVC.Controllers
{
    public class HeroicController : Controller
    {
        // GET: Heroic
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new HeroicService(userId);
            var model = service.GetHeroics();
            return View(model);
        }

        private HeroicService CreateHeroicService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new HeroicService(userId);
            return service;
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HeroicCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateHeroicService();
            if (service.CreateHeroic(model))
            {
                TempData["SaveResult"] = "Your heroic was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Your heroic could not be created.");

            return View("Index");
        }

        public ActionResult Details(int id)
        {
            var svc = CreateHeroicService();
            var model = svc.GetByHeroicId(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var svc = CreateHeroicService();
            var detail = svc.GetByHeroicId(id);
            var model =
                new HeroicEdit
                {
                    HeroicId = detail.HeroicId,
                    HeroicName = detail.HeroicName,
                    IsPersonalHeroic = detail.IsPersonalHeroic,
                    Description = detail.Description,
                    RequiredLevel = detail.RequiredLevel,
                    RequiredHeroic = detail.RequiredHeroic,

                    RequiredAgility = detail.RequiredAgility,
                    RequiredStrength = detail.RequiredStrength,
                    RequiredInstinct = detail.RequiredInstinct,
                    RequiredIntelligence = detail.RequiredIntelligence,
                    RequiredCharisma = detail.RequiredCharisma,
                    RequiredHealth = detail.RequiredHealth
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, HeroicEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.HeroicId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreateHeroicService();
            if (service.UpdateHeroic(model))
            {
                TempData["SaveResult"] = "Your heroic was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your heroic could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateHeroicService();
            var model = svc.GetByHeroicId(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var svc = CreateHeroicService();
            svc.DeleteHeroic(id);

            TempData["SaveResult"] = "Your heroic was deleted";

            return RedirectToAction("Index");
        }
    }
}

HomebrewRPG.WebMVC/Views/Heroic/Create.cshtml
@model HomebrewRPG.Models.HeroicModels.HeroicCreate

@{
    ViewBag.Title = "Create";
}

<div class="row padding">
    <div class="col-sm-12 col-md-6 col-md-offset-2 text-center container-fluid padding">
        <h2>Create a Heroic</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.HeroicName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.HeroicName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HeroicName, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredLevel, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredLevel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredLevel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredHeroic, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredHeroic, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredHeroic, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredAgility, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredAgility, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredAgility, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredStrength, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredStrength, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredStrength, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredInstinct, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredInstinct, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredInstinct, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredIntelligence, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredIntelligence, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredIntelligence, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredCharisma, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredCharisma, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredCharisma, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RequiredHealth, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RequiredHealth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RequiredHealth, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IsPersonalHeroic, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsPersonalHeroic)
                            @Html.ValidationMessageFor(model => model.IsPersonalHeroic, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>


<div class="row padding">
    <a href='@Url.Action("Index", "Heroic")' class="btn btn-default btn-sm">Back to Items</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomebrewRPG.WebMVC/Views/Heroic/Delete.cshtml
@model HomebrewRPG.Models.HeroicDetail

@{
    ViewBag.Title = "Delete";
}

<div class="row padding">

    <div class="col-sm-12 col-md-6 col-md-offset-2 text-center">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this item?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.HeroicName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.HeroicName)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="row padding">
                    <input type="submit" value="Delete Heroic Forever" class="btn bg-danger" />
                </div>
            }
            <div class="row padding">
                <a href='@Url.Action("Index", "Heroic")' class="btn btn-default">Back to Items</a>
            </div>
        </div>
    </div>
</div>

HomebrewRPG.WebMVC/Views/Heroic/Details.cshtml
@model HomebrewRPG.Models.HeroicDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HeroicDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HeroicId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeroicId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeroicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeroicName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPersonalHeroic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPersonalHeroic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredHeroic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredHeroic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredAgility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredAgility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredStrength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredStrength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredInstinct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredInstinct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredIntelligence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredIntelligence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredCharisma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredCharisma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredHealth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredHealth)
        </dd>

    </dl>
</div>
<p>
    <a href='@Url.Action("Index", "Heroic")' class="btn btn-primary btn-lg">Back to List</a>
</p>

HomebrewRPG.WebMVC/Views/Heroic/Edit.cshtml
@model HomebrewRPG.Models.HeroicModels.HeroicEdit

@{
    ViewBag.Title = "Edit";
}

<div class="row padding">
    <div class="col-sm-12 col-md-6 col-md-offset-2 text-center container-fluid padding">
        <h2>Create a Heroic</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HeroicId)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HeroicName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.HeroicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeroicName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredLevel, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredHeroic, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredHeroic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredHeroic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredAgility, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredAgility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredAgility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredStrength, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredStrength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredStrength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredInstinct, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredInstinct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredInstinct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredIntelligence, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredIntelligence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredIntelligence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredCharisma, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredCharisma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredCharisma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredHealth, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequiredHealth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredHealth, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsPersonalHeroic, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPersonalHeroic)
                    @Html.ValidationMessageFor(model => model.IsPersonalHeroic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
        }
    </div>
</div>


<div class="row padding">
    <a href='@Url.Action("Index", "Heroic")' class="btn btn-default btn-sm">Back to Items</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomebrewRPG.WebMVC/Views/Heroic/Index.cshtml
@model IEnumerable<HomebrewRPG.Models.HeroicModels.HeroicListItem>

@{
    ViewBag.Title = "Index";
}

<div class="row padding">

    <div class="col-sm-12 col-md-6 col-md-offset-2 text-center">

        <h2>Heroics</h2>
        <h3>Which item would you like to select?</h3>



        @foreach (var item in Model)
        {
            <div class="container-fluid padding">
                <div class="row">
                    <div class="card">
                        <div class="row">

                            <div class="col-xs-9">
                                <div class="row">
                                    <div class="col-xs-6">
                                        <h4>@Html.DisplayFor(modelItem => item.HeroicName)</h4>

                                    </div>
                                </div>
                                <div class="row padding">
                                    <div class="col-xs-6">
                                        <p class="fancy-text">
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </p>
                                    </div>
                                    <div class="col-xs-6">
                                        <p class="fancy-text">
                                            @Html.DisplayNameFor(model => model.IsPersonalHeroic):
                                            @Html.DisplayFor(modelItem => item.IsPersonalHeroic)
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <a href='@Url.Action("Delete", "Heroic", new { id = item.HeroicId })'><i class="fa fa-trash fa-lg"></i></a>
                            </div>
                            <div class="col-xs-3 padding">
                                <a href='@Url.Action("Edit", "Heroic", new { id = item.HeroicId })'><i class="fas fa-edit fa-lg"></i></a>
                            </div>
                        </div>
                        <a href='@Url.Action("Details", "Heroic", new { id = item.HeroicId })' class="btn btn-primary btn-lg">Select</a>
                    </div>
                </div>
            </div>
        }
        <div class="row padding">
            <a href='@Url.Action("Create", "Heroic")' class="btn btn-primary btn-lg">Create New</a>
        </div>
    </div>
</div>